language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

jdk:
  - oraclejdk8

env:
  - GRADLE_OPTS="-Xms256m -Xmx2048m -XX:MaxPermSize=4096m -XX:+CMSClassUnloadingEnabled" JAVA_OPTS="-Xms256m -Xmx2048m -XX:MaxPermSize=4096m" MALLOC_ARENA_MAX=2 CI=true

script:
  - ./gradlew clean build

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
